# Generated by Django 3.0.4 on 2020-03-26 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atracoes',
            new_name='Atracao',
        ),
    ]
